Repository home-assistant-libs/forecast_solar, pull requests merged in 2021-07, with the labels that each got.

#10 🚑 Fix the max() on empty sequence error
  forecast_solar/models.py
Labels: bugfix

#12 Fix finding peak
  forecast_solar/models.py
  setup.py
Labels: breaking-change

#9 New exceptions
  forecast_solar/__init__.py
  forecast_solar/exceptions.py
  forecast_solar/models.py
  setup.cfg
  test_forecast_solar.py
Labels: new-feature
