Repository home-assistant-libs/forecast_solar, pull requests merged in 2023-04, with the labels that each got.

#33 Add today's remaining production estimate
  README.md
  example.py
  forecast_solar/models.py
  tests/test_models.py
Labels: new-feature

#36 🎆Updates maintenance/license year to 2023
  LICENSE
  README.md
Labels: maintenance

#37 Fix #31 energy_current_hour will show wrong value with paid subscription
  forecast_solar/models.py
  tests/test_models.py
Labels: bugfix
